import type { Metadata } from "next";
import "./globals.css";

// components
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import StairTransition from "@/components/layout/StairTransition";
import PageTransition from "@/components/layout/PageTransition";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-Dana bg-gray-100 dark:bg-zinc-800">
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
        <Footer />
      </body>
    </html>
  );
}
